language: node_js
node_js:
  - "8.10"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add @angular/cli
  - ng --version

before_script:
  - npm install -g @angular/cli

script:
  - npm run build:prod
  - npm run test

notifications:
  email:
    on_failure: change
    on_success: change