language: node_js
node_js:
  - '10.16.3'
sudo: required

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - yarn build:prod
  - yarn test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist/resume
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
