language: node_js
node_js:
  - "8.10"

branches:
  only:
    - master

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli

script:
  - npm run build:prod
  - npm run test

notifications:
  email:
    on_failure: change
    on_success: change