import { Injectable } from '@angular/core'
import { Observable, of } from 'rxjs'

export interface LinkUrl {
  url: string
  text: string
  disabledTitle?: string
}

export interface Experience {
  title: string
  company: string
  position: string
  startDate: Date
  endDate?: Date
  description: string
  technologies: string[]
  imgUrl: string
  linkUrls?: LinkUrl[]
}

@Injectable()
export class ExperienceService {
  private experiences$: Observable<Experience[]>

  constructor() {
    this.experiences$ = of([
      {
        title: 'SCORE',
        company: 'SAIC',
        position: 'Junior Software Engineer',
        startDate: new Date(2020, 11),
        description: `Lead developer and product manager on a document editing and management application written using Vue,
         .net core, Entity Framework, Postgres, and AWS complete with accessibility, chrome lighthouse testing, integration and
         end to end testing using Cypress.`,
        technologies: ['Vue', 'Vuex', 'Cypress', '.NET Core', 'C#', 'Entity DB First', 'Postgres', 'AWS'],
        imgUrl: 'assets/img/saic-logo.png'
      },
      {
        title: 'DCATS',
        company: 'SAIC',
        position: 'Junior Software Engineer',
        startDate: new Date(2020, 11),
        description: `Revamped existing pipelines from scratch from on-prem Jenkins to AWS CodePipeline and Elastic Container
         Registry to integrate with a large internal cloud migration project`,
        technologies: ['CodePipeline', 'ECR', 'Jenkins', 'Docker', 'AWS'],
        imgUrl: 'assets/img/saic-logo.png'
      },
      {
        title: 'Renewals and Retentions Revamp',
        company: 'Infinite Energy',
        position: 'Dev Assistant',
        startDate: new Date(2020, 3),
        endDate: new Date(2020, 11),
        description: `Innovated and revamped the legacy system that the Renewals and Retentions (RnR) team, uses to keep track
         of the company's accounts that need to be renewed or retained. My primary responsibily was being the front end tech lead
         and pioneering the company's adoption of the new front end tech stack. Additionally wrote custom test libraries to aid
         developers test their code easily.`,
        technologies: ['React', 'Redux', 'Redux Toolkit', '.NET Core', 'C#', 'Entity DB First', 'MSSQL', 'Kubernetes'],
        imgUrl: 'assets/img/infinite-energy-logo.png'
      },
      {
        title: 'Transaction Switch Holds',
        company: 'Infinite Energy',
        position: 'Intern',
        startDate: new Date(2019, 9),
        endDate: new Date(2020, 1),
        description: `Quickly implemented and continue to maintain .net core microservice with sophisticated message passing to
         handle automatic switch hold transactions generated by the company’s CRM in response to COVID-19.`,
        technologies: ['.NET Core', 'C#', 'Microservice', 'Entity Code First', 'RabbitMQ', 'Docker', 'Kubernetes'],
        imgUrl: 'assets/img/infinite-energy-logo.png'
      },
      {
        title: 'Commercial Service Locations',
        company: 'Infinite Energy',
        position: 'Intern',
        startDate: new Date(2019, 9),
        endDate: new Date(2020, 1),
        description: `Engineered a .net core microservice with Entity Framework Code First DB, to manage company’s address
         import of up to 1.2 million addresses.`,
        technologies: ['.NET Core', 'C#', 'Microservice', 'Entity Code First', 'RabbitMQ', 'Docker', 'Kubernetes'],
        imgUrl: 'assets/img/infinite-energy-logo.png'
      },
      {
        title: 'FtpDownloads',
        company: 'Infinite Energy',
        position: 'Intern',
        startDate: new Date(2019, 7),
        endDate: new Date(2020, 3),
        description: `Developed .net core C# FTP microservice to handle uploads to and downloads from third parties.
         Responsible for implementing RabbitMQ messaging, integrating with Azure Blob Storage, and configuring deployment
         and environments for the service.`,
        technologies: ['.NET Core', 'C#', 'Microservice', 'Entity Code First', 'RabbitMQ', 'Docker', 'Kubernetes', 'SFTP'],
        imgUrl: 'assets/img/infinite-energy-logo.png'
      },
      {
        title: 'Common Messaging Platform',
        company: 'Ultimate Software',
        position: 'Intern',
        startDate: new Date(2019, 4),
        endDate: new Date(2019, 7),
        description: `Deployed and managed in house messaging systems for the rest of the domain teams in the company to use. Such systems
         and libraries include a Schema Registry, Kafka connect libraries, encryption/decryption libraries, RabbitMQ libraries, and spring
         starter libraries. All of this is written in Java using Spring.`,
        technologies: ['Kafka', 'RabbitMQ', 'Spring', 'Java'],
        imgUrl: 'assets/img/kafka-logo.png'
      },
      {
        title: 'NU Nav',
        company: 'Ultimate Software',
        position: 'Intern',
        startDate: new Date(2018, 4),
        endDate: new Date(2018, 7),
        description: `Ideated and implemented a design for an admin application
         used to manage the complex data of a cross-domain menu structure using Stencil.js and Angular 5.`,
        technologies: ['Stencil.js', 'Angular 5', 'Web Components'],
        imgUrl: 'assets/img/ultimate-software-logo.jpg'
      },
      {
        title: 'Transactor',
        company: 'Infinite Energy',
        position: 'Intern',
        startDate: new Date(2017, 7),
        endDate: new Date(2017, 11),
        description: `Maintained a C# back end system called Transactor responsible for processing thousands of
         customer energy usage data. Improved the company's internal tool used to manage customers and their data
         by adding features that assisted customer representatives in delivering unparalleled customer service.`,
        technologies: ['C#', 'ASP.NET'],
        imgUrl: 'assets/img/infinite-energy-logo.png'
      },
      {
        title: 'UltiDash',
        company: 'Ultimate Software',
        position: 'Intern',
        startDate: new Date(2017, 4),
        endDate: new Date(2017, 7),
        description: `Collaborated to develop an internal standup tool called UltiDash which integrated into Jira
         and the Aha! API's.`,
        technologies: ['C#', 'Angular', 'Web Api', 'Unity', 'Entity'],
        imgUrl: 'assets/img/ultimate-software-logo.jpg'
      },
      {
        title: 'Customer Website',
        company: 'Infinite Energy',
        position: 'Intern',
        startDate: new Date(2016, 7),
        endDate: new Date(2017, 4),
        description: `Engineered the payment feature on the company website so the customers can make payments and
         manage payment options.`,
        technologies: ['Angular.js v1.6', 'C#', 'Web Api', 'Unity', 'Entity'],
        imgUrl: 'assets/img/infinite-energy-logo.png',
        linkUrls: [
          {
            url: 'https://my.infiniteenergy.com/#!/login#shell',
            text: 'Live website'
          }
        ]
      },
      {
        title: 'Infinite Energy Industrial',
        company: 'Infinite Energy',
        position: 'Intern',
        startDate: new Date(2016, 4),
        endDate: new Date(2016, 9),
        description: 'I made a killer custom hybrid app with a fully functional back end and admin web app to manage it.',
        technologies: [
          'Angular 1.6',
          'Cordova',
          'Bootstrap',
          'C#',
          'Web Api',
          'Entity',
          'Unity',
          'Unit Testing'
        ],
        imgUrl: 'assets/img/infinite-energy-industrial-ios.PNG'
      }
    ])
  }

  getExperiences() {
    return this.experiences$
  }
}
